version: "3.9"

services:
  python_fastapi:
    image: python_fastapi
    build:
      context: ./pyf
    ports:
      - 50001:8000
    environment: 
      - POSTGRES_USER=gql
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    volumes:
      - ./pyf:/app

  python_tornado:
    image: python_tornado
    build:
      context: ./pyt
    ports:
      - 50002:80

  js:
    image: js
    build: 
      context: ./js
    environment:
      NODE_ENV: development
    ports:
      - 50003:3000
    volumes:
      - ./js:/usr/src/app

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=gql
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=anoyne@anywhere.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 50011:80

  nginx:
    build:
      context: ./nginx
    ports:
      - 50080:80
    depends_on:
      - postgres
      - js
      - python_fastapi
      - python_tornado 
